global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout: 15s
  # external_labels:
  #   monitor: 'geekshubs'

# rule_files:
#   - 'alert.rules'

# # Grafana URL: http://cortex:9009/api/prom
# remote_write:
#   - url: http://cortex:9009/api/prom/push

# alerting:
#   alertmanagers:
#     - scheme: http
#       static_configs:
#         - targets:
#             - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  # Doc: https://docs.docker.com/config/daemon/prometheus/
  # Linux Workaround: https://stackoverflow.com/a/67158212/1341168
  # - job_name: 'docker'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['host.docker.internal:9323']

  - job_name: 'scheduler-api'
    scrape_interval: 30s
    static_configs:
      - targets: ['scheduler:8000']